name: Build

on:
  push:

jobs:
  build-linux:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Calculate versions
      id: vers
      run: |
        PROJECT_VERSION=$(head -1  Version.txt)
        RELEASE_VERSION=`git describe --tags --exact-match` && true
        if [[ -n "$RELEASE_VERSION" ]]; then
          # rem Release
          RELEASE_FLAG=ON
          VERSION_SUFFIX="ow.r"
        else
          # Intermediate build
          RELEASE_FLAG=OFF
          VERSION_SUFFIX="ow.${{github.run_number}}"
        fi
        echo "::set-output name=project_ver::$PROJECT_VERSION"
        echo "::set-output name=release_flag::$RELEASE_FLAG"
        echo "::set-output name=ver_suffix::$VERSION_SUFFIX"        
        echo "::set-output name=release_ver::RELEASE_VERSION"

    - name: Display versions
      run: |
        echo "project_ver=${{steps.vers.outputs.project_ver}}"
        echo "release_flag=${{steps.vers.outputs.release_flag}}"
        echo "ver_suffix=${{steps.vers.outputs.ver_suffix}}"
        echo "release_ver=${{steps.vers.outputs.release_ver}}"
        
    - name: Build
      run: |
        cp File1.txt result-${{steps.vers.outputs.project_ver}}-${{steps.vers.outputs.ver_suffix}}.txt
        
    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: "result-${{steps.vers.outputs.project_ver}}-${{steps.vers.outputs.ver_suffix}}.txt"
        path: "result-${{steps.vers.outputs.project_ver}}-${{steps.vers.outputs.ver_suffix}}.txt"
