name: Build

on:
  push:

jobs:
  build-linux:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get release version
      id: get_vers
      run: |
        echo "##[set-output name=current_ver;]$(head -1 Version.txt)"
        echo "::set-output name=current_tag::$(git describe --tags --exact-match)"
        
    - name: Display result
      run: |
        echo "Version=${{steps.get_vers.output.current_ver}}"
        echo "Release=${{steps.get_vers.output.current_tag}}"
        
